apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: mysql-set
  labels:
    app: mysql

spec:
  serviceName: mysql-h
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
        type: mysql-db

    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: todoapp
          image: pmelero/mysql:todoapp-db
          ports:
            - containerPort: 3360

  replicas: 3

  # Also manage this previously created POD
  selector:
    matchLabels:
      app: mysql
