apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  ports:
    - protocol: TCP
      port: 3306 #target port is assumed to be the same as port

  selector:
    app: mysql
    type: mysql-db

  clusterIP: None #this creates a headless service
