apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  type: NodePort
  ports:
    - port: 5000 #target port is assumed to be the same as port
      protocol: TCP
  selector:
    app: todoapp
