apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-deployment

spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Password
            - name: MYSQL_DATABASE
              value: todoapp
          image: pmelero/mysql:todoapp-db
          ports:
            - containerPort: 3360

  replicas: 1

  # Also manage this previously created POD
  selector:
    matchLabels:
      app: mysql
