apiVersion: apps/v1

kind: Deployment

metadata:
  name: todoapp-deployment

spec:
  template:
    metadata:
      name: todoapp-pod
      labels:
        app: todoapp

    spec:
      containers:
        - name: todo-app
          env:
            - name: NODE_ENV
              value: production
          image: pmelero/todoapp:v6
          ports:
            - containerPort: 5000

  replicas: 3

  # Also manage this previously created POD
  selector:
    matchLabels:
      app: todoapp
