apiVersion: apps/v1

kind: Deployment

metadata:
  name: todoapp-deployment

spec:
  template:
    metadata:
      name: todoapp-pod
      labels:
        app: todoapp
        type: back-end

    spec:
      containers:
        - name: todo-app
          env:
            - name: NODE_ENV
              value: production
            - name: MYSQL_HOST
              value: db-service
          image: pmelero/todoapp:v8
          ports:
            - containerPort: 5000

  replicas: 3

  # Also manage this previously created PODs
  selector:
    matchLabels:
      app: todoapp
