apiVersion: v1

kind: Pod

metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: pmelero/mysql:todoapp-db
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password
        - name: MYSQL_DATABASE
          value: todoapp
      ports:
        - containerPort: 3360
