apiVersion: v1

kind: Pod

metadata:
  name: todoapp-pod
  labels:
    app: todoapp
    type: back-end
spec:
  containers:
    - name: todo-app
      image: pmelero/todoapp:nodeapp
      env:
        - name: NODE_ENV
          value: production
      ports:
        - containerPort: 5000
