apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: todoapp-replicaset

spec:
  ### POD creation definition ###
  template:
    metadata:
      name: todoapp-pod
      labels:
        app: todoapp

    spec:
      containers:
        - name: todo-app1
          image: pmelero/todoapp:nodeapp
          env:
            - name: NODE_ENV
              value: Production
          ports:
            - containerPort: 5000

  replicas: 3

  # Also manage this previously created POD
  selector:
    matchLabels:
      app: todoapp
